  version: '3.7'

  services:
    qdrant:
      image: qdrant/qdrant:${QDRANT_VERSION}
      container_name: qdrant
      ports:
        - 6333:6333
      env_file:
        - .env
      volumes:
        - qdrant_volume:/${SHARED_VOLUME_DIR}
    qdrant_preload:
      build:
        context: ./
        dockerfile: Dockerfile-qdrant-preload
      container_name: qdrant_preload
      env_file:
        - .env
      volumes:
        - qdrant_volume:/${QDRANT_PRELOAD_APP_NAME}/${SHARED_VOLUME_DIR}
    interactive:
      build:
        context: ./
        dockerfile: Dockerfile-interactive
      container_name: interactive
      ports:
        - 8080:8080
      env_file:
        - .env
      labels:
        application: 'interactive'
      stdin_open: true
      tty: true
      volumes:
        - model_volume:/data

  volumes:
    qdrant_volume:
    model_volume:
