# Pull main environment
ARG PYTHON_VERSION=3.8.10
FROM python:$PYTHON_VERSION AS base

ENV PYTHONUNBUFFERED=1
ENV DOCKER_ENTRYPOINT_FILE=docker-entrypoint-qdrant-preload.sh
ENV APP_NAME=${PRELOAD_APP_NAME}

# Define working directory
WORKDIR /$APP_NAME

RUN mkdir -p "/${SHARED_VOLUME_DIR}"
RUN pip install --upgrade pip --no-input
RUN pip install --no-cache-dir minio python-dotenv

# Update env variables
ENV PATH /root/.local/bin:$PATH
ENV PYTHONPATH "${PYTHONPATH}:/preload"

# Load files from repository
COPY /preload /$APP_NAME/preload
COPY /$DOCKER_ENTRYPOINT_FILE /$APP_NAME/$DOCKER_ENTRYPOINT_FILE

RUN chmod +x /$APP_NAME/$DOCKER_ENTRYPOINT_FILE

# Run command in shell file
CMD /$APP_NAME/$DOCKER_ENTRYPOINT_FILE
