# Pull main environment
ARG PYTHON_VERSION=3.8.10
FROM python:$PYTHON_VERSION AS base

ENV PYTHONUNBUFFERED=1
ENV DOCKER_ENTRYPOINT_FILE=docker-entrypoint-interactive.sh
ENV APP_NAME=${INTERACTIVE_APP_NAME}

# Define working directory
WORKDIR /$APP_NAME

ADD poetry.lock /$APP_NAME/poetry.lock
ADD pyproject.toml /$APP_NAME/pyproject.toml

RUN pip install --upgrade pip --no-input
RUN pip install --no-cache-dir poetry
RUN poetry export --without-hashes --format=requirements.txt > /$APP_NAME/requirements.txt
RUN pip install -r /$APP_NAME/requirements.txt

# Update env variables
ENV PATH /root/.local/bin:$PATH

# Load files from repository
COPY /api /$APP_NAME/api
COPY /interactive /$APP_NAME/interactive
COPY /metrics /$APP_NAME/metrics
COPY /$DOCKER_ENTRYPOINT_FILE /$APP_NAME/$DOCKER_ENTRYPOINT_FILE

RUN chmod +x /$APP_NAME/$DOCKER_ENTRYPOINT_FILE

# Expose port and run command in shell file
EXPOSE 8080

CMD /$APP_NAME/$DOCKER_ENTRYPOINT_FILE