  version: '3.7'

  services:
    qdrant-cloud:
      image: qdrant/qdrant:${QDRANT_VERSION}
      container_name: qdrant-cloud
      ports:
        - "${QDRANT_PORT}:${QDRANT_PORT}"
      env_file:
        - .env-cloud
        - .env
      volumes:
        - qdrant_volume:/${QDRANT_VOLUME_DIR}
    interactive-cloud:
      build:
        context: ./
        dockerfile: Dockerfile-interactive
        args:
            PYTHON_VERSION: python:${PYTHON_VERSION}
            INTERACTIVE_APP_NAME: ${INTERACTIVE_APP_NAME}
      container_name: interactive-cloud
      ports:
        - "${INTERACTIVE_PORT}:${INTERACTIVE_PORT}"
      env_file:
        - .env-cloud
        - .env
      labels:
        application: 'interactive'
      stdin_open: true
      tty: true
      volumes:
        - model_volume:/${MODEL_VOLUME_DIR}
        - qdrant_volume:/${QDRANT_VOLUME_DIR}


  volumes:
    qdrant_volume:
    model_volume:
