  version: '3.7'

  services:
    qdrant:
      image: qdrant/qdrant:v0.10.3
      container_name: qdrant
      ports:
      - 6333:6333
      env_file:
        - .env
      volumes:
        - ./data/qdrant_storage:/qdrant/storage
    interactive:
      build:
        context: ./
        dockerfile: Dockerfile-interactive
      container_name: interactive
      ports:
        - 8080:8080
      env_file:
        - .env
      labels:
        application: 'interactive'
      stdin_open: true
      tty: true
      depends_on:
        - "qdrant"